import styles from "./page.module.css";

export const metadata = {
  title: "Terms of Service | Buttons Technology",
  description: "Terms of service for Buttons Technology products.",
};

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <h1>Terms of Service</h1>
        <p className={styles.effective}>Effective date: February 12, 2026</p>

        <div className={styles.body}>
          <section>
            <h2>Agreement to Terms</h2>
            <p>
              By accessing or using any products or services provided by Buttons
              Technology, LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;),
              including the Clawsy application, you agree to be bound by these
              Terms of Service. If you do not agree to these terms, do not use
              our services.
            </p>
          </section>

          <section>
            <h2>Use of Services</h2>
            <p>
              You may use our services only in compliance with these terms and
              all applicable laws. You are responsible for your use of the
              services and for any content you create or store through them. You
              must be at least 13 years old to use our services.
            </p>
          </section>

          <section>
            <h2>User Content</h2>
            <p>
              You retain ownership of any content you create using our
              applications. We do not claim ownership of your data. Content
              generated by the AI within our applications is provided for your
              personal use and is yours to keep.
            </p>
          </section>

          <section>
            <h2>Intellectual Property</h2>
            <p>
              Our services, including all software, design, text, and
              trademarks, are owned by Buttons Technology, LLC and protected by
              intellectual property laws. You may not copy, modify, distribute,
              or reverse-engineer any part of our services without written
              permission.
            </p>
          </section>

          <section>
            <h2>Disclaimers</h2>
            <p>
              Our services are provided &quot;as is&quot; without warranties of
              any kind, whether express or implied. We do not guarantee that our
              services will be uninterrupted, error-free, or free of harmful
              components. AI-generated content may contain inaccuracies and
              should not be relied upon as professional advice.
            </p>
          </section>

          <section>
            <h2>Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Buttons Technology, LLC
              shall not be liable for any indirect, incidental, special,
              consequential, or punitive damages arising from your use of our
              services. Our total liability shall not exceed the amount you paid
              us in the twelve months prior to the claim.
            </p>
          </section>

          <section>
            <h2>Termination</h2>
            <p>
              We may suspend or terminate your access to our services at any
              time, with or without cause. You may stop using our services at
              any time. Upon termination, your right to use the services ceases
              immediately, though locally stored data remains on your device.
            </p>
          </section>

          <section>
            <h2>Changes to Terms</h2>
            <p>
              We may update these terms from time to time. If we make material
              changes, we will provide notice through our services. Continued use
              of the services after changes constitutes acceptance of the
              updated terms.
            </p>
          </section>

          <section>
            <h2>App-Specific Terms</h2>
            <p>
              Spark: Daily Motivation has its own app-specific terms at{" "}
              <a href="/spark/terms">/spark/terms</a>.
            </p>
          </section>

          <section>
            <h2>Contact</h2>
            <p>
              Questions about these terms can be sent to{" "}
              <a href="mailto:hello@buttonstechnology.com">
                hello@buttonstechnology.com
              </a>
              .
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
